-- REGULAR WO lifecycle: HOLD + CLOSED_WITH_SHORTFALL (operational fields).

ALTER TABLE `WorkOrder`
  ADD COLUMN `holdReason` ENUM('RM_SHORTAGE', 'MACHINE_BREAKDOWN', 'PRIORITY_SHIFT', 'CUSTOMER_HOLD', 'MANAGEMENT_HOLD', 'OTHER') NULL,
  ADD COLUMN `heldAt` DATETIME(3) NULL,
  ADD COLUMN `heldByUserId` INTEGER NULL,
  ADD COLUMN `holdRemarks` TEXT NULL,
  ADD COLUMN `shortfallQty` DECIMAL(18, 3) NULL,
  ADD COLUMN `closureReason` TEXT NULL,
  ADD COLUMN `closedAt` DATETIME(3) NULL,
  ADD COLUMN `closedByUserId` INTEGER NULL;

ALTER TABLE `WorkOrderLine`
  ADD COLUMN `shortfallQty` DECIMAL(18, 3) NULL;

ALTER TABLE `WorkOrder`
  ADD CONSTRAINT `WorkOrder_heldByUserId_fkey` FOREIGN KEY (`heldByUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `WorkOrder_closedByUserId_fkey` FOREIGN KEY (`closedByUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Extend SimpleStatus enum (MySQL)
ALTER TABLE `WorkOrder` MODIFY `status` ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'HOLD', 'CLOSED_WITH_SHORTFALL') NOT NULL DEFAULT 'PENDING';
