-- REGULAR WO production pause: PAUSED status + PRODUCTION_PAUSE hold reason.

ALTER TABLE `WorkOrder` MODIFY `status` ENUM(
  'PENDING',
  'IN_PROGRESS',
  'COMPLETED',
  'REJECTED',
  'HOLD',
  'PAUSED',
  'CLOSED_WITH_SHORTFALL'
) NOT NULL DEFAULT 'PENDING';

ALTER TABLE `WorkOrder` MODIFY `holdReason` ENUM(
  'RM_SHORTAGE',
  'MACHINE_BREAKDOWN',
  'PRIORITY_SHIFT',
  'CUSTOMER_HOLD',
  'MANAGEMENT_HOLD',
  'PRODUCTION_PAUSE',
  'OTHER'
) NULL;
