/**
 * FT-DEP-001 Milestone 3 Phase B — guided production configuration.
 *
 * Interactive or --from-args / env-file driven. Never overwrites shared/.env
 * without confirmation. Never prints passwords.
 *
 * Usage:
 *   node deployment/configure-env.js --home <FT_ERP_HOME> [--yes]
 *   node deployment/configure-env.js --home <FT_ERP_HOME> --non-interactive \
 *        --db-host 127.0.0.1 --db-port 3306 --db-name flowtix_erp \
 *        --db-user erp_user --db-password <secret> --port 4000 --jwt-secret <secret>
 */
const fs = require("fs");
const path = require("path");
const os = require("os");
const readline = require("readline");
const crypto = require("crypto");
const {
  parseEnvFile,
  buildDatabaseUrl,
  parseDatabaseUrl,
  maskValue,
  redactSecrets,
  nowIso,
} = require("./install-common");

function parseArgs(argv) {
  const out = {
    home: null,
    yes: false,
    nonInteractive: false,
    force: false,
    dbHost: null,
    dbPort: null,
    dbName: null,
    dbUser: null,
    dbPassword: null,
    port: null,
    jwtSecret: null,
    backupDir: null,
    logDir: null,
    hostname: null,
    ipv4: null,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--home" && argv[i + 1]) out.home = path.resolve(argv[++i]);
    else if (a === "--yes" || a === "-y") out.yes = true;
    else if (a === "--non-interactive") out.nonInteractive = true;
    else if (a === "--force") out.force = true;
    else if (a === "--db-host" && argv[i + 1]) out.dbHost = argv[++i];
    else if (a === "--db-port" && argv[i + 1]) out.dbPort = Number(argv[++i]);
    else if (a === "--db-name" && argv[i + 1]) out.dbName = argv[++i];
    else if (a === "--db-user" && argv[i + 1]) out.dbUser = argv[++i];
    else if (a === "--db-password" && argv[i + 1]) out.dbPassword = argv[++i];
    else if (a === "--port" && argv[i + 1]) out.port = Number(argv[++i]);
    else if (a === "--jwt-secret" && argv[i + 1]) out.jwtSecret = argv[++i];
    else if (a === "--backup-dir" && argv[i + 1]) out.backupDir = path.resolve(argv[++i]);
    else if (a === "--log-dir" && argv[i + 1]) out.logDir = path.resolve(argv[++i]);
    else if (a === "--hostname" && argv[i + 1]) out.hostname = argv[++i];
    else if (a === "--ipv4" && argv[i + 1]) out.ipv4 = argv[++i];
  }
  if (process.env.FT_ERP_HOME && !out.home) {
    out.home = path.resolve(String(process.env.FT_ERP_HOME).trim());
  }
  return out;
}

function ask(rl, question, defaultValue) {
  const hint = defaultValue != null && defaultValue !== "" ? ` [${defaultValue}]` : "";
  return new Promise((resolve) => {
    rl.question(`${question}${hint}: `, (answer) => {
      const a = String(answer || "").trim();
      resolve(a || (defaultValue != null ? String(defaultValue) : ""));
    });
  });
}

function askSecret(rl, question) {
  return new Promise((resolve) => {
    // readline cannot hide input portably without raw mode; warn operator
    rl.question(`${question} (input hidden in logs only): `, (answer) => {
      resolve(String(answer || ""));
    });
  });
}

function validateConfig(cfg) {
  const issues = [];
  if (!cfg.ftErpHome) issues.push("FT_ERP_HOME required");
  if (!cfg.dbHost) issues.push("Database host required");
  const port = Number(cfg.dbPort);
  if (!Number.isFinite(port) || port < 1 || port > 65535) issues.push("Database port invalid");
  if (!cfg.dbName || !/^[A-Za-z0-9_]+$/.test(cfg.dbName)) {
    issues.push("Database name must be alphanumeric/underscore");
  }
  if (!cfg.dbUser) issues.push("Database username required");
  if (!cfg.dbPassword || cfg.dbPassword.length < 4) {
    issues.push("Database password required (min 4 characters)");
  }
  const httpPort = Number(cfg.port);
  if (!Number.isFinite(httpPort) || httpPort < 1 || httpPort > 65535) {
    issues.push("HTTP port invalid");
  }
  if (!cfg.jwtSecret || cfg.jwtSecret.length < 16) {
    issues.push("JWT secret must be at least 16 characters");
  }
  if (/CHANGE_ME/i.test(cfg.dbPassword) || /CHANGE_ME/i.test(cfg.jwtSecret)) {
    issues.push("Placeholders CHANGE_ME are not allowed");
  }
  return issues;
}

function detectIpv4() {
  const ifaces = os.networkInterfaces();
  for (const name of Object.keys(ifaces)) {
    for (const info of ifaces[name] || []) {
      if (info && info.family === "IPv4" && !info.internal) return info.address;
    }
  }
  return "127.0.0.1";
}

function renderEnvFile(cfg) {
  const databaseUrl = buildDatabaseUrl({
    user: cfg.dbUser,
    password: cfg.dbPassword,
    host: cfg.dbHost,
    port: cfg.dbPort,
    database: cfg.dbName,
  });
  const lines = [
    `# Flowtix ERP production environment`,
    `# Generated by configure-env.js at ${nowIso()}`,
    `# Do not commit this file. Passwords are stored only here.`,
    ``,
    `DATABASE_URL="${databaseUrl}"`,
    `JWT_SECRET="${cfg.jwtSecret.replace(/"/g, '\\"')}"`,
    `NODE_ENV=production`,
    `PORT=${cfg.port}`,
    `FT_ERP_HOME=${cfg.ftErpHome}`,
    ``,
    `# Optional overrides`,
    `BACKUP_STORAGE_DIR=${cfg.backupDir}`,
    `LOG_DIR=${cfg.logDir}`,
    ``,
    `# Server identity (informational — used by LAN-ACCESS notes)`,
    `# SERVER_HOSTNAME=${cfg.hostname}`,
    `# SERVER_IPV4=${cfg.ipv4}`,
    ``,
  ];
  return lines.join("\n");
}

function printSummary(cfg) {
  console.log("");
  console.log("======== Configuration Summary (secrets masked) ========");
  console.log(`  FT_ERP_HOME     : ${cfg.ftErpHome}`);
  console.log(`  Hostname        : ${cfg.hostname}`);
  console.log(`  IPv4            : ${cfg.ipv4}`);
  console.log(`  HTTP port       : ${cfg.port}`);
  console.log(`  Database host   : ${cfg.dbHost}`);
  console.log(`  Database port   : ${cfg.dbPort}`);
  console.log(`  Database name   : ${cfg.dbName}`);
  console.log(`  Database user   : ${cfg.dbUser}`);
  console.log(`  Database pass   : ${maskValue(cfg.dbPassword)}`);
  console.log(`  JWT secret      : ${maskValue(cfg.jwtSecret)}`);
  console.log(`  Backup dir      : ${cfg.backupDir}`);
  console.log(`  Log dir         : ${cfg.logDir}`);
  console.log(`  LAN URL example : http://${cfg.ipv4}:${cfg.port}/`);
  console.log("========================================================");
  console.log("");
}

async function collectInteractive(home, existing) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const existingUrl = existing.DATABASE_URL ? parseDatabaseUrl(existing.DATABASE_URL) : null;
  try {
    const hostname = await ask(rl, "Server hostname", os.hostname());
    const ipv4 = await ask(rl, "Server LAN IPv4", detectIpv4());
    const port = await ask(rl, "HTTP port", existing.PORT || "4000");
    const dbHost = await ask(rl, "Database host", (existingUrl && existingUrl.host) || "127.0.0.1");
    const dbPort = await ask(rl, "Database port", (existingUrl && existingUrl.port) || "3306");
    const dbName = await ask(rl, "Database name", (existingUrl && existingUrl.database) || "flowtix_erp");
    const dbUser = await ask(rl, "Database username", (existingUrl && existingUrl.user) || "erp_user");
    let dbPassword = await askSecret(rl, "Database password");
    if (!dbPassword && existingUrl && existingUrl.password) dbPassword = existingUrl.password;
    let jwtSecret = await askSecret(rl, "JWT secret (blank = generate)");
    if (!jwtSecret) jwtSecret = existing.JWT_SECRET || crypto.randomBytes(32).toString("hex");
    const backupDir = await ask(rl, "Backup directory", path.join(home, "backups", "db"));
    const logDir = await ask(rl, "Log directory", path.join(home, "logs"));
    return {
      ftErpHome: home,
      hostname,
      ipv4,
      port: Number(port),
      dbHost,
      dbPort: Number(dbPort),
      dbName,
      dbUser,
      dbPassword,
      jwtSecret,
      backupDir,
      logDir,
    };
  } finally {
    rl.close();
  }
}

function collectNonInteractive(args, home, existing) {
  const existingUrl = existing.DATABASE_URL ? parseDatabaseUrl(existing.DATABASE_URL) : {};
  return {
    ftErpHome: home,
    hostname: args.hostname || os.hostname(),
    ipv4: args.ipv4 || detectIpv4(),
    port: args.port || Number(existing.PORT) || 4000,
    dbHost: args.dbHost || existingUrl.host || "127.0.0.1",
    dbPort: args.dbPort || existingUrl.port || 3306,
    dbName: args.dbName || existingUrl.database || "flowtix_erp",
    dbUser: args.dbUser || existingUrl.user || "erp_user",
    dbPassword: args.dbPassword || existingUrl.password || "",
    jwtSecret: args.jwtSecret || existing.JWT_SECRET || crypto.randomBytes(32).toString("hex"),
    backupDir: args.backupDir || path.join(home, "backups", "db"),
    logDir: args.logDir || path.join(home, "logs"),
  };
}

async function confirm(rlOrNull, yes) {
  if (yes) return true;
  if (!rlOrNull) return false;
  const a = await ask(rlOrNull, "Save this configuration to shared\\.env? [y/N]", "N");
  return /^y(es)?$/i.test(a);
}

async function runConfigure(options = {}) {
  const home = path.resolve(options.home);
  fs.mkdirSync(path.join(home, "shared"), { recursive: true });
  fs.mkdirSync(path.join(home, "logs"), { recursive: true });
  const envPath = path.join(home, "shared", ".env");
  const existing = parseEnvFile(envPath);
  const existed = fs.existsSync(envPath);

  let cfg;
  if (options.nonInteractive) {
    cfg = collectNonInteractive(options, home, existing);
  } else {
    cfg = await collectInteractive(home, existing);
  }

  const issues = validateConfig(cfg);
  if (issues.length) {
    return { ok: false, issues, envPath, saved: false };
  }

  printSummary(cfg);

  if (existed && !options.force) {
    console.log(`[configure-env] WARNING: ${envPath} already exists.`);
    console.log("[configure-env] Existing file will NOT be overwritten without confirmation.");
  }

  let proceed = options.yes || options.force;
  if (!proceed) {
    if (options.nonInteractive && !options.yes && !options.force) {
      return {
        ok: false,
        issues: ["Non-interactive mode requires --yes (or --force to overwrite)"],
        envPath,
        saved: false,
      };
    }
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    try {
      proceed = await confirm(rl, false);
      if (existed && proceed) {
        const overwrite = await ask(rl, "Overwrite existing shared\\.env? Type YES to confirm", "");
        proceed = overwrite === "YES";
      }
    } finally {
      rl.close();
    }
  } else if (existed && options.force) {
    proceed = true;
  } else if (existed && options.yes && !options.force) {
    // --yes alone should not silently overwrite
    return {
      ok: false,
      issues: ["shared\\.env exists — pass --force to overwrite, or edit manually"],
      envPath,
      saved: false,
    };
  }

  if (!proceed) {
    return { ok: false, issues: ["Configuration save cancelled"], envPath, saved: false };
  }

  // Backup existing env (without echoing secrets)
  if (existed) {
    const bak = path.join(
      home,
      "shared",
      `.env.bak-${new Date().toISOString().replace(/[:.]/g, "-")}`,
    );
    fs.copyFileSync(envPath, bak);
  }

  const body = renderEnvFile(cfg);
  fs.writeFileSync(envPath, body, "utf8");

  // Write LAN access note (no secrets)
  const lanPath = path.join(home, "LAN-ACCESS.txt");
  fs.writeFileSync(
    lanPath,
    [
      "Flowtix ERP — Client Access",
      "Server (this PC): http://127.0.0.1:" + cfg.port + "/",
      "LAN clients:      http://" + cfg.hostname + ":" + cfg.port + "/",
      "                  http://" + cfg.ipv4 + ":" + cfg.port + "/",
      "Port source: shared\\.env PORT",
      "",
    ].join("\n"),
    "utf8",
  );

  const summaryPath = path.join(home, "logs", "configure-env-summary.txt");
  fs.writeFileSync(
    summaryPath,
    redactSecrets(
      [
        `configuredAt=${nowIso()}`,
        `home=${home}`,
        `host=${cfg.hostname}`,
        `ipv4=${cfg.ipv4}`,
        `port=${cfg.port}`,
        `dbHost=${cfg.dbHost}`,
        `dbPort=${cfg.dbPort}`,
        `dbName=${cfg.dbName}`,
        `dbUser=${cfg.dbUser}`,
        `dbPassword=***`,
        `jwtSecret=***`,
        `backupDir=${cfg.backupDir}`,
        `logDir=${cfg.logDir}`,
      ].join("\n") + "\n",
    ),
    "utf8",
  );

  return { ok: true, issues: [], envPath, saved: true, summaryPath, lanPath };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.home) {
    console.error("[configure-env] ERROR: --home <FT_ERP_HOME> required");
    process.exit(1);
  }
  const result = await runConfigure(args);
  if (!result.ok) {
    console.error("[configure-env] FAILED:");
    for (const i of result.issues) console.error(`  - ${i}`);
    process.exit(2);
  }
  console.log(`[configure-env] Saved ${result.envPath}`);
  console.log(`[configure-env] Summary ${result.summaryPath}`);
  console.log(`[configure-env] LAN notes ${result.lanPath}`);
  process.exit(0);
}

if (require.main === module) {
  main().catch((e) => {
    console.error("[configure-env] FATAL:", e instanceof Error ? e.message : String(e));
    process.exit(1);
  });
}

module.exports = { runConfigure, validateConfig, renderEnvFile, printSummary };
