-- Enquiry: add OPEN for new records; no DRAFT→OPEN or QUOTED data migration
ALTER TABLE `Enquiry` MODIFY `status` ENUM(
  'DRAFT',
  'OPEN',
  'PENDING',
  'FEASIBLE',
  'NOT_FEASIBLE',
  'QUOTED',
  'PO_RECEIVED',
  'CLOSED'
) NOT NULL DEFAULT 'PENDING';

-- SimpleStatus: IN_PROGRESS (shared across WorkOrder, Quotation, PO, etc.; only WorkOrder logic sets IN_PROGRESS)
ALTER TABLE `Feasibility` MODIFY `status` ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED') NOT NULL;
ALTER TABLE `Quotation` MODIFY `status` ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE `CustomerPO` MODIFY `status` ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE `RmPurchaseOrder` MODIFY `status` ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE `WorkOrder` MODIFY `status` ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
