/**
 * Standard module codes for ActivityLog.module (string constants; not Prisma enums).
 */
const ACTIVITY_MODULES = Object.freeze({
  SALES_ORDER: "SALES_ORDER",
  REQUIREMENT_SHEET: "REQUIREMENT_SHEET",
  WORK_ORDER: "WORK_ORDER",
  PRODUCTION: "PRODUCTION",
  QC: "QC",
  DISPATCH: "DISPATCH",
  SALES_BILL: "SALES_BILL",
  PURCHASE_BILL: "PURCHASE_BILL",
  TALLY_EXPORT: "TALLY_EXPORT",
  STOCK: "STOCK",
});

/**
 * Standard action codes for ActivityLog.action.
 */
const ACTIVITY_ACTIONS = Object.freeze({
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  APPROVED: "APPROVED",
  APPROVAL_CANCELLED: "APPROVAL_CANCELLED",
  LOCKED: "LOCKED",
  FINALIZED: "FINALIZED",
  REVERSED: "REVERSED",
  DELETED: "DELETED",
  CANCELLED: "CANCELLED",
  EXPORTED: "EXPORTED",
  EXPORT_FAILED: "EXPORT_FAILED",
  CLOSED: "CLOSED",
  REOPENED: "REOPENED",
});

/** ActivityLog.entityType — document or aggregate key for filtering history. */
const ACTIVITY_ENTITY_TYPES = Object.freeze({
  SALES_ORDER: "SALES_ORDER",
  REQUIREMENT_SHEET: "REQUIREMENT_SHEET",
  WORK_ORDER: "WORK_ORDER",
  PRODUCTION_ENTRY: "PRODUCTION_ENTRY",
  QC_ENTRY: "QC_ENTRY",
  DISPATCH: "DISPATCH",
  SALES_BILL: "SALES_BILL",
  PURCHASE_BILL: "PURCHASE_BILL",
});

module.exports = {
  ACTIVITY_MODULES,
  ACTIVITY_ACTIONS,
  ACTIVITY_ENTITY_TYPES,
};
